import { GameInfo, GameType } from '../types';

export const GAME_DEFINITIONS: Record<GameType, GameInfo> = {
  cal: {
    id: 'cal',
    title: 'Arm Calibration',
    category: 'warm',
    categoryLabel: 'Warm-up',
    durationMinutes: 10,
    description: 'Throw 3 darts at sequential segment groups (20→6→3, 6→3→11, 3→11→20, 11→20→Bull) to dial in your throwing stroke and release consistency.',
    subtitle: '10 min · 4-target progression sequence',
    icon: 'Activity',
  },
  wheel: {
    id: 'wheel',
    title: 'The Wheel',
    category: 'warm',
    categoryLabel: 'Warm-up',
    durationMinutes: 10,
    description: 'Throw 1 dart at 20, 1 dart at 19, and 1 dart at 18. Record your visit result: 1 Hit, 2 Hits, 3 Hits, or Miss to warm up your arm.',
    subtitle: '10 min · 20 → 19 → 18 targets · 1/2/3 hits or Miss',
    icon: 'RotateCw',
  },
  score: {
    id: 'score',
    title: 'High Score',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 20,
    description: '20 minutes of pure scoring at the Treble 20 (or chosen target). Log each 3-dart visit (0–180) to evaluate your 3-dart average, First 9, and distribution.',
    subtitle: '20 min · Power scoring average & distribution',
    icon: 'TrendingUp',
  },
  score1: {
    id: 'score1',
    title: 'High Score (20 min)',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 20,
    description: '20 minutes of pure scoring at Treble 20. Log visits 0–180 to evaluate your 3-dart scoring average.',
    subtitle: '20 min · 3-dart scoring average',
    icon: 'TrendingUp',
  },
  score2: {
    id: 'score2',
    title: 'High Score',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 20,
    description: '20 minutes of power scoring at Treble 20.',
    subtitle: '20 min · Scoring drill',
    icon: 'TrendingUp',
  },
  1219: {
    id: '1219',
    title: '121 in 9 Darts',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Fast-paced checkout ladder. 9 darts per target. Checkouts in ≤ 3 darts (1 visit) lock a checkpoint! Fails drop back to checkpoint.',
    subtitle: '20 min · ≤ 3 darts checkpoint lock',
    icon: 'Flame',
  },
  12112: {
    id: '12112',
    title: '121 in 12 Darts',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Classic checkout ladder. 12 darts per target. Checkouts in ≤ 6 darts lock a checkpoint! Checkouts in 7–12 advance target.',
    subtitle: '20 min · ≤ 6 darts checkpoint lock',
    icon: 'Target',
  },
  catch40: {
    id: 'catch40',
    title: 'Catch 40',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Progress through targets 41 up to 80 (40 checkout scenarios). 6 darts per target. Target advances by 1 on every attempt.',
    subtitle: '20 min · Targets 41–80 · 6 darts each',
    icon: 'Zap',
  },
  bull: {
    id: 'bull',
    title: 'Bull Warm-up',
    category: 'warm',
    categoryLabel: 'Bull Warm-up',
    durationMinutes: 10,
    description: 'Target the center of the board. Log Bull (50 pts / Red), 25 (Outer Ring / Green), or Miss (0 pts) to hone center-board focus.',
    subtitle: '10 min · Bull (50) / 25 / Miss scoring',
    icon: 'Crosshair',
  },
  triple: {
    id: 'triple',
    title: 'Triple Lock',
    category: 'solo',
    categoryLabel: 'Triple Lock',
    durationMinutes: 20,
    isCountUp: false,
    description: '20-minute countdown challenge from 20 down to 1 and Bull finish. Hit 0–1 = reset to checkpoint; 2 = advance; 3 = LOCK checkpoint. Finish the full ladder before time expires, or log your progress at the 20-min buzzer!',
    subtitle: '20 min countdown · Lock 20→1 & Bull finish',
    icon: 'Lock',
  },
  '301': {
    id: '301',
    title: '301 Match Play',
    category: 'solo',
    categoryLabel: '301 Legs',
    durationMinutes: 20,
    description: '20 minutes of continuous 301 solo legs (standard double-out finishing). Track total completed legs, best leg (fewest darts), and 3-dart average.',
    subtitle: '20 min · Solo legs & fewest-darts record',
    icon: 'Award',
  },
  dartbot: {
    id: 'dartbot',
    title: 'X01 vs Bot & Solo',
    category: 'match',
    categoryLabel: 'X01 Match',
    durationMinutes: null,
    isCountUp: true,
    description: 'Full standard 501, 301, or 701 match play. Choose to practice Solo or play vs customizable AI DartBot (skill 35 to 110+ average & custom checkout %).',
    subtitle: '501 / 301 / 701 · Play Solo or vs AI DartBot',
    icon: 'Bot',
  },
};
