import { GameInfo, GameType } from '../types';

export const GAME_DEFINITIONS: Record<GameType, GameInfo> = {
  cal: {
    id: 'cal',
    title: 'Arm Calibration',
    category: 'warm',
    categoryLabel: 'Warm-up',
    durationMinutes: 10,
    description: 'Throw 3 darts at sequential segment groups (20→6→3, 6→3→11, 3→11→20, 11→20→Bull) to dial in your throwing stroke and release consistency.',
    subtitle: '10 min · 4-target progression sequence',
    icon: 'Activity',
  },
  wheel: {
    id: 'wheel',
    title: 'The Wheel',
    category: 'warm',
    categoryLabel: 'Warm-up',
    durationMinutes: 10,
    description: 'Throw 1 dart at 20, 1 dart at 19, and 1 dart at 18. Record your visit result: 1 Hit, 2 Hits, 3 Hits, or Miss to warm up your arm.',
    subtitle: '10 min · 20 → 19 → 18 targets · 1/2/3 hits or Miss',
    icon: 'RotateCw',
  },
  align: {
    id: 'align',
    title: 'Align',
    category: 'warm',
    categoryLabel: 'Warm-up',
    durationMinutes: 10,
    description: 'Throw 1 dart at each target across 4 cardinal axes passing through Bull: (20→Bull→3, 11→Bull→6, 3→Bull→20, 6→Bull→11). Singles, doubles, trebles, and 25/Bull all count as hits.',
    subtitle: '10 min · Cross & alignment axes warm-up drill',
    icon: 'Compass',
  },
  score: {
    id: 'score',
    title: 'High Score',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 10,
    description: '10 minutes of pure scoring at Treble 20. Log each 3-dart visit (0–180) to evaluate your 3-dart average, First 9, and distribution.',
    subtitle: '10 min · Power scoring average & distribution',
    icon: 'TrendingUp',
  },
  score1: {
    id: 'score1',
    title: 'High Score (10 min)',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 10,
    description: '10 minutes of pure scoring at Treble 20. Log visits 0–180 to evaluate your 3-dart scoring average.',
    subtitle: '10 min · 3-dart scoring average',
    icon: 'TrendingUp',
  },
  score2: {
    id: 'score2',
    title: 'High Score',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 10,
    description: '10 minutes of power scoring at Treble 20.',
    subtitle: '10 min · Scoring drill',
    icon: 'TrendingUp',
  },
  switchblade: {
    id: 'switchblade',
    title: 'Switchblade',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 10,
    description: '10 minutes of target switching across standard 5-throw cycles (T20-T20-T20, T20-T20-T19, T20-T20-T18, T20-T20-T17, T20-T20-Bull). Enter hits per dart.',
    subtitle: '10 min · T20-T20-Switch sequences · Precision switching',
    icon: 'Crosshair',
  },
  powerswitch: {
    id: 'powerswitch',
    title: 'Power Switch',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 10,
    description: 'Every visit starts at T20. Hit Treble (3 pts) to STAY on target; Miss, Single, or Double switches to the next target (T20→T19→T18). A perfect visit is 180.',
    subtitle: '10 min · Every visit starts T20 · Treble stays, Miss switches',
    icon: 'Zap',
  },
  bigscores: {
    id: 'bigscores',
    title: 'Big Scores',
    category: 'score',
    categoryLabel: 'Scoring',
    durationMinutes: 10,
    description: '10-minute power sequence across key segments (20 → 19 → 18 → 17 → Bull). 3 darts per visit on each target. Repeating 5-visit cycles.',
    subtitle: '10 min · 20 → 19 → 18 → 17 → Bull cycle · Power scoring',
    icon: 'Trophy',
  },
  1219: {
    id: '1219',
    title: '121 in 9 Darts',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Fast-paced checkout ladder. 9 darts per target. Checkouts in ≤ 3 darts (1 visit) lock a checkpoint! Fails drop back to checkpoint.',
    subtitle: '20 min · ≤ 3 darts checkpoint lock',
    icon: 'Flame',
  },
  12112: {
    id: '12112',
    title: '121 in 12 Darts',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Classic checkout ladder. 12 darts per target. Checkouts in ≤ 6 darts lock a checkpoint! Checkouts in 7–12 advance target.',
    subtitle: '20 min · ≤ 6 darts checkpoint lock',
    icon: 'Target',
  },
  catch40: {
    id: 'catch40',
    title: 'Catch 40',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Progress through targets 41 up to 80 (40 checkout scenarios). 6 darts per target. Target advances by 1 on every attempt.',
    subtitle: '20 min · Targets 41–80 · 6 darts each',
    icon: 'Zap',
  },
  cochallenge: {
    id: 'cochallenge',
    title: 'Checkout Challenge',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 20,
    description: 'Select your starting checkout (default 21). Finish in max 3 darts (501-style). Hit = +10 to next out; Miss = -1 (down to start). Highest checkout finished within 20 min is your score!',
    subtitle: '20 min · Hit = +10, Miss = -1 · High Checkout score',
    icon: 'Crosshair',
  },
  boomerang: {
    id: 'boomerang',
    title: 'Doubles Boomerang',
    category: 'finish',
    categoryLabel: 'Finishing',
    durationMinutes: 10,
    description: 'Hit each double clockwise starting with D1 (D1, D18, D4...). 1 dart per double. Hit locks the double and you move on; miss returns to it on the next throw. Use as few darts as possible to clear the board!',
    subtitle: '10 min · Clockwise D1→D20 · Hit locks, Miss returns',
    icon: 'RotateCw',
  },
  a1practice: {
    id: 'a1practice',
    title: 'A1 - Practice',
    category: 'solo',
    categoryLabel: 'Singles',
    durationMinutes: 10,
    description: 'Hit 2 out of 3 darts on each LARGE SINGLE FIELD of the numbers 20 to 12. Click on HIT if you hit 2 or 3 of the current numbers LARGE SINGLE FIELD and click MISS if you hit less than 2. Clear 3 successful rounds per number to eliminate it from the board!',
    subtitle: '10 min · 20→12 · 2/3 hits to advance (3 hits to clear)',
    icon: 'Target',
  },
  bigsingles: {
    id: 'bigsingles',
    title: 'Big Singles',
    category: 'solo',
    categoryLabel: 'Singles',
    durationMinutes: 10,
    description: 'Hit only the big single field of the current number from 1 to 20. Throw all 3 darts at the current number. Complete full 1 to 20 rounds before the 10-minute timer expires.',
    subtitle: '10 min · 1→20 · Grouping drill with Intermediate & Advanced rules',
    icon: 'Crosshair',
  },
  bigsingles_intermediate: {
    id: 'bigsingles_intermediate',
    title: 'Big Singles (Intermediate)',
    category: 'solo',
    categoryLabel: 'Singles',
    durationMinutes: 10,
    description: 'Hit only the big single field from 1 to 20. Intermediate rules: 2 or 3 hits move to next number, 1 hit stays, 0 hits go back 1 number.',
    subtitle: '10 min · 1→20 · 2/3 hits advance, 1 stay, 0 back 1',
    icon: 'Crosshair',
  },
  bigsingles_advanced: {
    id: 'bigsingles_advanced',
    title: 'Big Singles (Advanced)',
    category: 'solo',
    categoryLabel: 'Singles',
    durationMinutes: 10,
    description: 'Hit only the big single field from 1 to 20. Advanced rules: 3 hits move to next number, 2 hits stay, 1 hit goes back 1 number, 0 hits go back 2 numbers.',
    subtitle: '10 min · 1→20 · 3 hits advance, 2 stay, 1 back 1, 0 back 2',
    icon: 'Crosshair',
  },
  bull: {
    id: 'bull',
    title: 'Bull Warm-up',
    category: 'warm',
    categoryLabel: 'Bull Warm-up',
    durationMinutes: 10,
    description: 'Target the center of the board. Log Bull (50 pts / Red), 25 (Outer Ring / Green), or Miss (0 pts) to hone center-board focus.',
    subtitle: '10 min · Bull (50) / 25 / Miss scoring',
    icon: 'Crosshair',
  },
  triple: {
    id: 'triple',
    title: 'Triple Lock',
    category: 'solo',
    categoryLabel: 'Triple Lock',
    durationMinutes: 20,
    isCountUp: false,
    description: '20-minute countdown challenge from 20 down to 1 and Bull finish. Hit 0–1 = reset to checkpoint; 2 = advance; 3 = LOCK checkpoint. Finish the full ladder before time expires, or log your progress at the 20-min buzzer!',
    subtitle: '20 min countdown · Lock 20→1 & Bull finish',
    icon: 'Lock',
  },
  '301': {
    id: '301',
    title: '301 Match Play',
    category: 'solo',
    categoryLabel: '301 Legs',
    durationMinutes: 20,
    description: '20 minutes of continuous 301 solo legs (standard double-out finishing). Track total completed legs, best leg (fewest darts), and 3-dart average.',
    subtitle: '20 min · Solo legs & fewest-darts record',
    icon: 'Award',
  },
  dartbot: {
    id: 'dartbot',
    title: 'X01 vs Bot & Solo',
    category: 'match',
    categoryLabel: 'X01 Match',
    durationMinutes: null,
    isCountUp: true,
    description: 'Full standard 501, 301, or 701 match play. Choose to practice Solo or play vs customizable AI DartBot (skill 35 to 110+ average & custom checkout %).',
    subtitle: '501 / 301 / 701 · Play Solo or vs AI DartBot',
    icon: 'Bot',
  },
};
